AWSTemplateFormatVersion: "2010-09-09"
Description: Create EC2 Instance.

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-026b57f3c383c2eec
      InstanceType: t2.micro
      KeyName: sidkey
      
